# Site settings
title: "Bela: The platform for beautiful interaction"
email: info@bela.io
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "https://disastrid.github.io/bela_dec2018" # the subpath of your site, e.g. /blog/
#baseurl: ""
twitter_username: belaPlatform
github_username:  belaPlatform

# Build settings
markdown: kramdown
