boards:
  - title: Bela
    desc: The original Bela board has everything you need to start creating beautifully interactive applications. With 8 16-bit analog I/O and 16 digital I/O you can hook up all your favourite sensors and devices, and get programming with our browser-based IDE. Bela is compatible with our multiplexer and audio expander capelets, and has on-board stereo amps, making this our most fully-featured system. Available as a starter kit (full system of BeagleBone Black, USB cable, Bela cape and two audio adapter cables) or as the stand-alone cape.
    image: bela.png
    url: https://shop.bela.io/bela
    specs:
      - spec: Stereo audio I/O
      - spec: 8 channels of 16-bit analog I/O
      - spec: 16 digital I/O
      - spec: On-board speaker amps
  - title: Bela Mini
    desc: 'In 2018 we condensed all the most popular features of Bela into one tiny system that fits in more places than ever before. The Bela Mini is 1/3 the size of the Original Bela, but still powerful - it has 8 16-bit analog inputs, 16 digital I/O and stereo audio I/O. Bela Mini uses the same Bela software as the original, so you still get access to our browser-based IDE in a much smaller form factor. Available as a starter kit (fully assembled board, USB cable, SD card and 2 audio adapter cables), or as a standalone kit.'
    image: bela_mini.png
    specs:
      - spec: Stereo audio I/O
      - spec: 8 channels of 16-bit analog input
      - spec: 16 digital I/O
    url: https://shop.bela.io/bela-mini
accessories:
  - title: Trill Touch Sensors
    image: trill_family.png
    desc: Trill is a family of touch sensors designed to make it easy to bring high-resolution touch sensing to your interactive projects. There are five Trill types, all designed by the team that brought you Bela but compatible with a wide range of systems. 
    url: #
  - title: CTAG Multichannel system
    image: ctag.png
    desc: CTAG is a multichannel audio system for Bela, developed in collaboration with Henrik Langer and Robert Manzke from the CTAG group at Kiel University. There are two versions available, CTAG FACE (4 channels in, 8 channels out) and CTAG BEAST (8 channels in, 16 channels out).
    url: https://shop.bela.io/ctag
  - title: Multiplexer Capelet
    desc: If 8 channels of analog input aren't enough, expand up to 64 channels with the Bela Multiplexer Capelet. (Compatible only with Bela, not compatible with Bela Mini.)
    image: mux.png
    url: https://shop.bela.io/bela-accessories/bela-mux-capelet
  - title: Audio Expander Capelet
    desc: Turn your 8 analog I/O into 4 additional stereo I/O with the Bela Audio Expander. (Compatible only with Bela, not compatible with Bela Mini.)
    image: audio_expander.png
    url: https://shop.bela.io/bela-accessories/bela-audio-expander-capelet
modular:
  - title: SALT
    desc: SALT is a fully programmable Bela synth module created in collaboration with Rebel Technology. This module has 4 CV and 4 trigger, expandable up to 8 of each with the SALT+ expander. Comes fully assembled and ready to use, including an embedded Bela system.
    image: salt.png
    url: https://shop.bela.io/modular/salt
  - title: PEPPER
    desc: PEPPER is a kit for building a module to integrate your Bela unit with the world of Modular and Eurorack synths. PEPPER includes a custom-designed, bare PCB that comes with a list of common through-hole components for you to source, as well as a black faceplate. Solder it together, attach PEPPER to your Bela system and you can start prototyping and experimenting with Bela and your modular synth. 
    image: pepper.png
    url: https://shop.bela.io/modular/pepper
trill:
  - title: Trill Bar
    desc: Trill Bar is a multi-touch slider that can detect up to 5 touches at once. As well as touch position, Trill Bar also senses the size of individual touches, acting like a pressure sensor.
    image: bar.png
    dimensions: 112mm x 22mm
    url: http://google.com
  - title: Trill Square
    desc: Trill Square is a x/y touch pad that senses the position of one touch across two axes, as well as touch size - ideal for interfaces and projects that require a single touch to control two parameters. 
    image: square.png
    dimensions: 74mm x 74mm
    url: http://google.com
  - title: Trill Craft
    desc: Trill Craft is a 30-channel breakout board for making custom touch interfaces out of anything conductive. Trill Craft is perfect for creating complex interfaces from conductive fabric, copper tape, metal, wire, fruit, water, and any other conductive material.
    image: craft.png
    dimensions: 54mm x 25mm
    url: http://google.com
  - title: Trill Hex
    desc: Trill Hex is a hexagonal, 2-axis x/y sensor which also senses touch size. Its hexagonal shape makes it ideal for experimenting with tessellation and creating isomorphic keyboards.
    image: hex.png
    dimensions: 46.5mm (edge to edge), 52mm (corner to corner)
    url: http://google.com
  - title: Trill Ring
    desc: Trill Ring is a one-axis circular slider that can detect up to 5 simultaneous touches as well as touch size. Trill Ring is the perfect controller for varying filters, sequencers, frequencies and more. Want to add visual feedback and a button? Trill Ring is designed to fit within a Neopixels ring, and fits an arcade button in the central hole.
    image: ring.png
    dimensions: 52mm (outer diameter), 28mm (inner diameter)
    url: http://google.com